services:
  nodeapp:
    build: .
    container_name: node_app_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    networks:
      - app-network

  mysql:
    profiles:
      - database
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=services
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/src/db:/sql-scripts
      - ${PWD}/scripts/mysql-entrypoint.sh:/mysql-entrypoint.sh
      - mysql_data:/var/lib/mysql
    command: ["bash", "/mysql-entrypoint.sh"]
    networks:
      - app-network
      
  ollama:
    profiles:
      - ai
    image: ollama/ollama:latest
    container_name: ollama_container
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:${PWD}/.ollama
    networks:
      - app-network

  nginx:
    profiles:
      - web
    image: nginx:alpine
    container_name: nginx_proxy_container
    restart: unless-stopped
    ports:
      - "80:80" # Maps host port 80 to container port 80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodeapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
  mysql_data: