services:
  nodeapp:
    build: .
    container_name: node_app_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - app-network

  mysql:
    profiles:
      - database
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_container
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - app-network

  ollama:
    profiles:
      - ai
    image: ollama/ollama:latest
    container_name: ollama_container
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_container
    restart: unless-stopped
    ports:
      - "80:80" # Maps host port 80 to container port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodeapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: